### ISSUE TITLE
Station tab enhancement

### ISSUE THREAD

**Issue by eduran84** [eduran84/LTN_Tracker#11]
Based on the discussion in the forums: https://forums.factorio.com/viewtopic.php?f=214&t=64842#p398277

#### Ideal outcome
- Clickable column-headers, sorting entire table by clicked column
- Additional filters for station name and state.

You would be able to do "show only yellow and blue stops with 'Iron' in their name", with results sorted by whatever column is currently clicked.

#### Thoughts
- Clickable column headers:
  - requires sorting of potentially large tables -> bad for performance
  - could be either done **(a)** in the background (small impact on performance, but all the time) or **(b)** when a header is clicked (large impact on performance on that tick)
  - Multiplayer is a headache. Either store sorted tables for all possible kinds of sorting (requires (a) from above) or store one sorted table for each player and recalculating that whenever a column header is clicked.
  - Multiplayer issue 2: if option (b) is implemented, all players have to run the sorting whenever anyone clicks a column header, even if their UI is closed. Otherwise the result would be a desync.

- Filtering:
  - Has to be done whenever the filter changes.
  - Would work with unsorted stop table, which is the form in which stops are currently available.
 
#### Performance issue
- Performance for populating the table with hundreds of stops is terrible. Can easily take tens of milliseconds, resulting in noticeable stutter. Not too bad in single-player, as it only happens when the UI is opened/refreshed. In MP, it would happen whenever anyone opens or refreshes their UI.
- There is very little to be done about it, as most of the time is spent on adding LuaGuiElements.
- Only solution would be to limit the number of stops displayed, combined with extra buttons to change pages. Not sure if desirable.

**Comment by Yousei9** [comment]
Does every client execute the whole UI generation or just the one opening it?
If you have 3 players each viewing a different tab, does each client also populate the others tabs!?
That sounds like a massive performance drain.

I'm no fan of clicking through pages, Shuttle train light does that and it's looking not as good as your current complete list and it takes much longer to find a stop if you don't know what page it's on.
Waiting a tiny bit longer for a complete list to populate or trimming results down through networkID sounds like a better way to go.

**Comment by eduran84** [comment]
> If you have 3 players each viewing a different tab, does each client also populate the others tabs!?

Yes, that's how it is. They don't render the UI elements, but the lua code has to run in sync on all clients.

**Comment by eduran84** [comment]
Implemented with 0.9.1.
