### ISSUE TITLE
[0.8.3] Cargo Alert improvement

### ISSUE THREAD

**Issue by Yousei9** [eduran84/LTN_Tracker#12]
**Problem:**
Player uses station designs with unfiltered inserters.
The current way of only checking cargo when leaving a requester does not alert when a train unloaded incorrect cargo at a dumb requester station.

**Solution:**
- [x] check train cargo against loading list when trains leave provider and requester
- [x] rename leftover cargo to wrong or incorrect cargo
- [x] Cargo Alerts should remain visible until manually cancelled by a player

**Comment by eduran84** [comment]
> check train cargo against loading list when trains leave provider and requester
Which loading list do you refer to? I can see how loading incorrect cargo would be detectable by comparing shipment and train content. But how would I know that incorrect cargo was unloaded?

**Comment by Yousei9** [comment]
Sorry for the confusion, loading list = delivery.shipment.
I say loading list when talking about what should be loaded in and out of a train and shipment when it's inside the train or reserved.

**Comment by eduran84** [comment]
Makes sense. I'll look into it tonight.

**Comment by eduran84** [comment]
Going down that route would force me into listening for train status changes and figure out when a train leaves a provider. Any chance you could add an on_train_left_provider event, similiar to on_delivery_completed?

**Comment by Yousei9** [comment]
Sure, I could do that.
I am handling that case anyway, so firing one more event shouldn't impact performance.

A lazy way would be to check if delivery shipment counts have changed. Though that will fail for deliveries loaded to max train capacity

**Comment by Yousei9** [comment]
Do you want anything beside the data sent in on_delivery_completed?

**Comment by Yousei9** [comment]
PS: I just noticed there already is a flag to indicate when trains leave a stop. delivery.pickupDone

**Comment by eduran84** [comment]
To use the flag I would have to check every delivery with pickupDone == true against a list of all deliveries with pickupDone == false from the previous update to notice the change. Which means storing an additional table and performing the check on every update. Possible, but inefficient.

**Comment by eduran84** [comment]
I've pushed my first attempt at this to the 0.9.3 branch. It relies on the on_delivery_pickup_complete_event. If it's inconvenient for you to keep that around, I could do without it, but having the event is preferable (see above).
If you are worried about event creep, you could consolidate all delivery events into one on_delivery_updated event, including the current data and a failed = true/false flag.

**Comment by Yousei9** [comment]
I'm fine with having dedicated events for different states of a delivery.
Wouldn't consolidating them make discerning between finished and pickup complete more involved?

The names of my events rub me wrong a lot more. No idea why I added "get_" prefix and "_event" suffix.
