### ISSUE TITLE
LTN 1.10.2 - Interface changes

### ISSUE THREAD

**Issue by Yousei9** [eduran84/LTN_Tracker#14]
I'm going to change the event data in the next release to be in line with base factorio events.

New Api documentation is at the bottom of this post: https://forums.factorio.com/viewtopic.php?f=214&t=51072&p=397844#p397844

Let me know if I missed something important.

**Comment by eduran84** [comment]
Did you remove Provided/Requested from dispatcher data, or just forgot to list them? I am using those to populate the inventory.

**Comment by Yousei9** [comment]
I removed those.
Provided and Requests have messy data formats compared to their by_stop counterparts. 
Having two different data formats containing the same information feels redundant and doesn't offer much speed benefits.

**Comment by eduran84** [comment]
I made some changes and will test them against your 1.10.2 branch when I am home. Nothing missing as far as I can tell.

No, RequestAge is currently not used for anything. Could maybe trigger an alert when it goes above a certain threshold?

**Comment by Yousei9** [comment]
an alert before ltn drops the delivery?
could be a feature, if you want that info i can put it in

oh, also I now update provided item counts when creating a delivery.
Cant believe no one noticed this thing was lagging behind a full update cycle. :D
