### ISSUE TITLE
0.9.4 Incorrect cargo alert on normal shipment.

### ISSUE THREAD

**Issue by Yousei9** [eduran84/LTN_Tracker#17]
I have two Requesters that always trigger incorrect cargo alert when they have lubricant delivered to them.
Attached is the log where Refinery - Load (Acid & Lubricant) > Research Lab 1 - Unload 2 triggered the alert.

My first guess would be alerts get confused by seeing stack threshold and normal threshold.

[factorio-current.log](https://github.com/eduran84/LTN_Tracker/files/2973927/factorio-current.log)

**Comment by eduran84** [comment]
Floating point fluids strike again... I am checking if the result of get_fluid_contents() matches the amount reported by LTN exactly, which fails in some cases due to rounding errors. I will change the comparison to allow some tolerance for fluids.

**Comment by Yousei9** [comment]
Fluid deliveries cant be merged with items or other fluid deliveries. It's just not really possible to build a station capable of doing that, so LTN doesn't even support that.

This means you could potentially simplify the checks a lot.
leaving provider: check if fluid names match between train and delivery
leaving requester: check if any fluid is in the train

**Comment by eduran84** [comment]
Did 0.9.5 fix the issue? Never saw it myself, so somewhat hard to test.

**Comment by Yousei9** [comment]
Still happens in 0.9.5.

**Comment by eduran84** [comment]
Can you send me another log created with 0.9.5? I changed the logging slightly. I guess it was not a floating point issue.

**Comment by Yousei9** [comment]
This is odd.... doing the same as 15min ago in the same save. 
Now the false alert won't fire, regardless of logging active or not.
