### ISSUE TITLE
LTN Tracker autodisables itself on headless

### ISSUE THREAD

**Issue by Psychotonikum** [eduran84/LTN_Tracker#20]
**Error message or bug description**
Activated LTN Tracker on Factorio headless server. LTN_Tracker autodisables itself during restart (mod-list.json). Clients can't join with mod active.

**To Reproduce**
Try to play with LTN-Tracker enabled on Factorio headless server version.

**LTN Tracker version**
`0.9.7`

**Factorio version**
`Factorio 0.17.21 (build 44074, linux64, headless)`

**Log file**
[factorio-current.log](https://github.com/eduran84/LTN_Tracker/files/3015390/factorio-current.log)

**Comment by eduran84** [comment]
I am unable to reproduce the issue. Creating and joining a game on a headless server with LTNT active works on my end. I suggest you try the [Technical Help forum](https://forums.factorio.com/viewforum.php?f=49).

**Comment by Psychotonikum** [comment]
`Factorio 0.17.23 (build 44171, linux64, headless)` does not have the issue anymore.
