### ISSUE TITLE
LTN Tracker Crash

### ISSUE THREAD

**Issue by PiggyWhiskey** [eduran84/LTN_Tracker#23]
![image](https://user-images.githubusercontent.com/9373995/56183695-ad275200-6056-11e9-9697-9de706c6247b.png)

I updated my mods and had this crash when closing LTN Combinator GUI.

The issue is resolved if I open LTN Tracker GUI first (Needs 2 Clicks) and then open LTN Combinator GUI.

Save attached for testing:
[0.17 Modded Bobs normal - Attempt 3-1.zip](https://github.com/eduran84/LTN_Tracker/files/3083121/0.17.Modded.Bobs.normal.-.Attempt.3-1.zip)

On that save, clicking the LTN combinator if front of you will crash when you close it.

**Comment by eduran84** [comment]
Thank you for the helpful save. Will be fixed in 0.10.5.
