### ISSUE TITLE
Error connecting to server since 0.17.34 update

### ISSUE THREAD

**Issue by chris-stormideas** [eduran84/LTN_Tracker#24]
**Error message or bug description**
Unable to connect to server since updating to 0.17.34.  Error in attached

![Screenshot from 2019-04-26 11-17-51](https://user-images.githubusercontent.com/44848490/56821852-10627280-6815-11e9-8bc5-82585bebbcb0.png)

**To Reproduce**
Update factorio and connect to a server with LTNT installed, makes no difference if it is installed locally

**LTN Tracker version**
0.10.*
Have tried with different versions, same result.  Logs are from 0.10.6

**Factorio version**
0.17.34

**Log file**
Attached are my log files and the server log files
[local-factorio-current.log](https://github.com/eduran84/LTN_Tracker/files/3122147/local-factorio-current.log)
[server-factorio-current.log](https://github.com/eduran84/LTN_Tracker/files/3122149/server-factorio-current.log)

**Comment by chris-stormideas** [comment]
Tried to get .7 logs, and the issue went away.  Will close

**Comment by eduran84** [comment]
There is something weird going on with saves created in 0.17.33 and loaded into 0.17.34 for the first time. Some just work, some show the error you described and some desync.

**Comment by chris-stormideas** [comment]
Yea, it was fairly consistently broke, tired many variations to get it to work before I reaised the issue.  And then first time after, it works.  The joys of software.

Thanks for the great work btw

On 26 Apr 2019 11:57, eduran <notifications@github.com> wrote:

There is something weird going on with saves created in 0.17.33 and loaded into 0.17.34 for the first time. Some just work, some show the error you described and some desync.

**Comment by eduran84** [comment]
In case someone else comes across this issue:
Shut down your server after failing to join. This will make the server save the game. Restart the server from that saved game. Joining should now be possible again. This process worked on a number of saves for me.
