### ISSUE TITLE
Mark beta version as incompatible to Stable

### ISSUE THREAD

**Issue by Yousei9** [eduran84/LTN_Tracker#26]
Adding this to info.json in the beta release will prevent players from even trying to run beta and stable at the same time.

`"dependencies": ["base >= 0.17.11", "LogisticTrainNetwork >= 1.10.7", "OpteraLib >= 0.1.5", "!LTN_Tracker" ]`

Similarily you could make the stable deactivate itself when it sees the beta. No idea what factorio would do if you do both though.

**Comment by eduran84** [comment]
Thanks, will add this for the next version.
