### ISSUE TITLE
LTNT Beta: Train info panel sends trains to wrong depot

### ISSUE THREAD

**Issue by Yousei9** [eduran84/LTN_Tracker#28]
Train information panel sends trains to wrong depots:

![2019-05-21-10-30-13-9864980](https://user-images.githubusercontent.com/8436934/58080795-26651800-7bb4-11e9-9fc3-b0ffdd3ee07a.png)

[factorio-current.zip](https://github.com/eduran84/LTN_Tracker/files/3201517/factorio-current.zip)

**Comment by eduran84** [comment]
Should be fixed in 0.1.7. Good thing you found that, there was a huge bug in the way my data processing worked.
